### ISSUE TITLE
Quest Mending Fences

### ISSUE THREAD

**Issue by TivTiv** [AbyssWoW/BugTracker#28]
Player: Tivam , Rogue Alli Location: Stormpeaks

I am unable to finish the Quest Mending Fences because I already finished the Quest A Spark of Hope ( https://www.wowhead.com/quest=12956/a-spark-of-hope ). The Phasing start after u finish A Spark of Hope so you are unable to kill further mobs for the Quest Mending Fences. This means you would miss 40k Reputation.

**Comment by Udesii** [comment]
Fixed

**Comment by Udesii** [comment]
I will check it out. But intresting, I can't reproduce the issue with 3 chars.

**Comment by TivTiv** [comment]
I try to explain. 
I start "mending fences" then i start "A Spark of Hope".  I finish "A spark of Hope" and bring it back to Questgiver. Go back to the Questarea to continue "mending fences" but the phasing is there.

**Comment by Udesii** [comment]
I see your problem, I would look into it, when I can.

**Comment by TivTiv** [comment]
I finished the quest because my Wife killed the required mobs while im nearby. Fixed it for me but can still happen to others.
